services:
  server:
    build: .
    container_name: cardapp23
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/games
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--logpath", "/dev/null"]

volumes:
  mongo-data:
  db_data:
  
